# Generated by Django 5.2.7 on 2025-10-05 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0002_tickethistory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="status",
            field=models.CharField(
                choices=[
                    ("Open", "Open"),
                    ("In Progress", "In Progress"),
                    ("Closed", "Closed"),
                    ("Resolved", "Resolved"),
                ],
                default="Open",
                max_length=20,
            ),
        ),
    ]
